services:
  wikigo:
    build:
      context: .
      dockerfile: Dockerfile
    image: dannyswat/wikigo:latest
    container_name: wikigo
    ports:
      - "8080:8080"
    volumes:
      - ./server/data:/app/data
      - ./server/media:/app/media
      - ./server/conf:/app/conf
    restart: unless-stopped
